### ISSUE TITLE
Enhance button hover style with cursor change and color highlight

### ISSUE THREAD

**Issue by rakesh-nj** [lokendarjangid/gemini-chat#40]
I would like to propose adding the following CSS code to improve the visual feedback and user experience when hovering over buttons:

```css
.button:hover {
    cursor: pointer;
    color: yellowgreen;
}
```
I believe this would be a positive addition to the user experience. I If it is an acceptable issue please assign it to me.

I am interested to contibute to this project further . I request you to consider me as a contributor
